# Generated by Django 5.1.2 on 2024-10-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorgeneral",
            name="especialidad",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="laboratorio",
            name="ciudad",
            field=models.CharField(default="Desconocido", max_length=255),
        ),
        migrations.AddField(
            model_name="laboratorio",
            name="pais",
            field=models.CharField(default="Desconocido", max_length=255),
        ),
    ]
